### ISSUE TITLE
Does it work ?

### ISSUE THREAD

**Issue by schmurtzm** [dparnell/esp32-nabaztag-arduino#1]
Hi, I was looking for a way to replace the original board of my Nabaztag V1 when I found your repo.
Could you tell me more ?
Is it already working ? What can we control ?
You emulate the original firmware in an ESP32 ?
What are the limitations ?
How to plug it , have you a diagram or something ?

Thank you ;)

**Comment by dparnell** [comment]
Hi, this code currently works with some test hardware I have. It runs a heavily modified version of the firmware from the original hardware. It would run existing firmware, but I have my own firmware that I run on my current rabbit. I tried to make all the hardware I have fit into the shell of my rabbit but it would not all go in due to the limited space.

What is really needed is a new custom PCB to make it all fit in there. Since I have two rabbits and one of them is dead I'm currently exploring the idea of removing the processor, RAM, flash and LED drivers from the PCB and growing the ESP32 onto the board by soldering lines onto the appropriate traces. This will allow me to continue the project.

So, to answer your question, yes it kind of works already. The current code controls 5 neopixels and the same audio hardware as used in the original so all the sounds work as expected

**Comment by dparnell** [comment]
Oh, and you probably want to use this version instead: https://github.com/dparnell/esp32-nabaztag

**Comment by schmurtzm** [comment]
Thanks for your answer :)
OK, I'm interested to make some test !
Yes I had the same idea : we can't do anything of a V1 board, it connects only in WEP and it's not acceptable for the security point of view. For the V2 board there's a modified firmware [which supports WPA2](https://www.journaldulapin.com/2018/04/19/tagtag-wpa2/) but in my case modify the existing PCB seems to be a good idea.

So from what I see in the code : 
Button (at top of the head) : GPIO5
Audio out : GPIO36 ? 12,13,14,27 ?
LED RGB : GPIO22 ?

A pinout diagram or some advices could help a lot to wire all these :)

Some questions : 

- Can we control the ears of the rabbit too ?
- Does it support TTS ?

**Comment by dparnell** [comment]
I have yet to code up the motor control stuff, but I imagine it should be pretty simple once I have it running on the real hardware. I just haven't had a chance to do much with it over the last couple of years as I've been busy with other things.
I'm going to archive this repo as it was a dead end due to the ESP32 Arduino stuff not being able to send raw packets. That was the main reason behind switching to the ESP SDK stuff.

**Comment by dparnell** [comment]
If you want to continue this discussion start a new issue in this project: https://github.com/dparnell/esp32-nabaztag
